/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("BooksObjectPageObjectPage journey");

        opaTest("Navigate to BooksObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheBooksListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheBooksListGenerated.onTable().iCheckRows();
            When.onTheBooksListGenerated.onTable().iPressRow(0);

            Then.onTheBooksObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheBooksObjectPageGenerated.iCheckNumberOfSections(3);
            When.onTheBooksObjectPageGenerated.iPressSectionIconTabFilterButton("GeneratedFacet1");
            Then.onTheBooksObjectPageGenerated.iCheckSection({ section: "GeneratedFacet1" });
            Then.onTheBooksObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Title" });
            Then.onTheBooksObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Genre" });
            Then.onTheBooksObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "PublishedAt" });
            Then.onTheBooksObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Pages" });
            Then.onTheBooksObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "price" });
            When.onTheBooksObjectPageGenerated.iPressSectionIconTabFilterButton("EntryInformation");
            Then.onTheBooksObjectPageGenerated.iCheckSection({ section: "EntryInformation" });
            Then.onTheBooksObjectPageGenerated.onForm({ section: "EntryInformation" }).iCheckField({ property: "modifiedAt" });
            Then.onTheBooksObjectPageGenerated.onForm({ section: "EntryInformation" }).iCheckField({ property: "modifiedBy" });
            Then.onTheBooksObjectPageGenerated.onForm({ section: "EntryInformation" }).iCheckField({ property: "createdAt" });
            Then.onTheBooksObjectPageGenerated.onForm({ section: "EntryInformation" }).iCheckField({ property: "createdBy" });
            When.onTheBooksObjectPageGenerated.iPressSectionIconTabFilterButton("Chapters");
            Then.onTheBooksObjectPageGenerated.iCheckSection({ section: "Chapters" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});